line-length = 88
indent-width = 4

[lint]
select = [
    "E",     # Error
    "F",     # Pyflakes
    "ARG",   # flake8-unused-arguments
    "W",     # Warning
    "I",     # isort
    "Q",     # flake8-quotes
    "N",     # pep8-naming
    "RET",   # flake8-return
    "SIM",   # flake8-simplify
    "PD",    # pandas-vet
    "NPY",   # NumPy-specific rules
    "PERF",  # Perflint
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
